# Generated by Django 5.2.6 on 2025-09-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.IntegerField(default=0),
        ),
    ]
